name: Francis Davey's Open Data Law and Licensing
description: Slides, handouts and other information connected with my Open Data Law and Licensing course
author: Francis Davey
author_email: contact@francisdavey.co.uk
markdown: kramdown
markdown_ext: md